
CREATE TABLE public.tb_movie (
    id bigint NOT NULL,
    count integer,
    image character varying(255),
    score double precision,
    title character varying(255)
);

ALTER TABLE public.tb_movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tb_score (
    id bigint NOT NULL,
    value double precision,
    movie_id bigint,
    user_id bigint
);

ALTER TABLE public.tb_score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tb_user (
    id bigint NOT NULL,
    email character varying(255)
);

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO public.tb_user VALUES (1, 'hilbo.cardeira@gmail.com');
INSERT INTO public.tb_user VALUES (2, 'Irineu.cardeira@gmail.com');
INSERT INTO public.tb_user VALUES (3, 'Hugo.cardeira@gmail.com');
INSERT INTO public.tb_user VALUES (4, 'lazaro.cardeira@gmail.com');

INSERT INTO public.tb_movie VALUES (1, 0, 'https://i1.wp.com/image.tmdb.org/t/p/w342/nJUHX3XL1jMkk8honUZnUmudFb9.jpg?resize=250%2C370&ssl=1',0.0, 'Helo');
INSERT INTO public.tb_movie VALUES (2, 0, 'https://i0.wp.com/image.tmdb.org/t/p/w342/u1XrqlIjQt2ghnA8nprpPiFzSzR.jpg?resize=250%2C370&ssl=1',0.0, 'Animais Fantásticos');
INSERT INTO public.tb_movie VALUES (3, 0, 'https://image.tmdb.org/t/p/w342/tFURJnWv5qW58x4OOrXt1GQEyr1.jpg?resize=250%2C370&ssl=1',0.0, 'Furiosa');
INSERT INTO public.tb_movie VALUES (4, 0, 'https://www.themoviedb.org/t/p/w342/odVv1sqVs0KxBXiA8bhIBlPgalx.jpg',0.0, 'Moonfall');
INSERT INTO public.tb_movie VALUES (5, 0, 'https://www.themoviedb.org/t/p/w342/3Ut50akEyfV5QDjUuA199cHmpaK.jpg',0.0, 'Morte no Nilo');
INSERT INTO public.tb_movie VALUES (6, 0, 'https://i1.wp.com/image.tmdb.org/t/p/w342/miVUacc6Or0XNnJkwUsZ3tb1ryM.jpg?resize=250%2C370&ssl=1',0.0, 'Ambulância');
INSERT INTO public.tb_movie VALUES (7, 0, 'https://i0.wp.com/image.tmdb.org/t/p/w342/pneaBHGQ5BqGJ3afxlPezL5czZB.jpg?resize=250%2C370&ssl=1',0.0, 'Mayas');
INSERT INTO public.tb_movie VALUES (8, 0, 'https://i0.wp.com/www.themoviedb.org/t/p/w342/td69unYCXVQ2Y0HpekqrnZlsVFT.jpg?resize=250%2C370&ssl=1',0.0, 'Passageiro 666');
INSERT INTO public.tb_movie VALUES (9, 0, 'https://i0.wp.com/image.tmdb.org/t/p/w342/rbNc44otT6VRd7QpxqlUAMyByaQ.jpg?resize=250%2C370&ssl=1',0.0, 'Better Call Saul ');
INSERT INTO public.tb_movie VALUES (10, 0, 'https://i0.wp.com/image.tmdb.org/t/p/w342/dYBWgaJwQ5RXk9I4S6gN0LGq0P9.jpg?resize=250%2C370&ssl=1',0.0, 'Terra sem lei');
INSERT INTO public.tb_movie VALUES (11, 0, 'https://i0.wp.com/image.tmdb.org/t/p/w342/f3zQhtFn8EzHgdPXoDPAtcGQnSf.jpg?resize=250%2C370&ssl=1',0.0, 'Escolha ou morra');
INSERT INTO public.tb_movie VALUES (12, 0, 'https://filmestorrentflix.net/wp-content/uploads/wordpress-popular-posts/153845-first_image-270x370.jpg',0.0, 'Infinit Storm');
INSERT INTO public.tb_movie VALUES (13, 0, 'https://filmestorrentflix.net/wp-content/uploads/wordpress-popular-posts/153700-first_image-270x370.jpg',0.0, 'O Homem do norte');
INSERT INTO public.tb_movie VALUES (14, 0, 'https://filmestorrentflix.net/wp-content/uploads/wordpress-popular-posts/153149-first_image-270x370.jpg',0.0, 'X');
INSERT INTO public.tb_movie VALUES (15, 0, 'https://www.themoviedb.org/t/p/w342/32TXmY7GHlXhgGG7Wzrurm1okG5.jpg',0.0, 'Gold');
INSERT INTO public.tb_movie VALUES (16, 0, 'https://www.themoviedb.org/t/p/w342/7BRRlZ5XWz9EC4pjPy66zKgQwCk.jpg',0.0, 'Presque');

SELECT pg_catalog.setval('public.hibernate_sequence', 240, true);

SELECT pg_catalog.setval('public.tb_movie_id_seq', 18, true);

SELECT pg_catalog.setval('public.tb_score_id_seq', 1, true);

SELECT pg_catalog.setval('public.tb_user_id_seq', 4, true);

ALTER TABLE ONLY public.tb_movie
    ADD CONSTRAINT tb_movie_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_score
    ADD CONSTRAINT tb_score_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_score
    ADD CONSTRAINT fk23yhb6qop0f6hnb72hcorm3cv FOREIGN KEY (movie_id) REFERENCES public.tb_movie(id);


ALTER TABLE ONLY public.tb_score
    ADD CONSTRAINT fkl8lgmbrjoav0thqqtqx6vrr4k FOREIGN KEY (user_id) REFERENCES public.tb_user(id);



